// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB90jFUOHWzzjf3noON22gGtymgOl6ID5Q',
    appId: '1:792286831602:web:ae8f523d9d2e2fc262816b',
    messagingSenderId: '792286831602',
    projectId: 'chitchat-3d21b',
    authDomain: 'chitchat-3d21b.firebaseapp.com',
    storageBucket: 'chitchat-3d21b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXo5PkPr1EsUO3-NElOomMorzCljnnNuA',
    appId: '1:792286831602:android:ba628a813e2743bd62816b',
    messagingSenderId: '792286831602',
    projectId: 'chitchat-3d21b',
    storageBucket: 'chitchat-3d21b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD03uoR1f00ykAkY-ueSuUd-Fk9LqKp2o',
    appId: '1:792286831602:ios:1c7f51e28db3e36f62816b',
    messagingSenderId: '792286831602',
    projectId: 'chitchat-3d21b',
    storageBucket: 'chitchat-3d21b.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );
}
